# Generated by Django 2.2.1 on 2019-05-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='SQLData',
        ),
    ]
